### ISSUE TITLE
Fix Readme

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/dot-response-header#2]
* remove extra **Dot** from `Dot\Dot\ResponseHeader\ConfigProvider::class,`
* provide instruction for adding `ResponseHeaderMiddleware` to the pipeline
* (optional) provide a `response-header.global.php.dist` file and instruct developers on where to copy it
```php
<?php

declare(strict_types=1);

return [
    'dot_response_headers' => [
        /**
         * Global headers - applied to all routes
         */
        '*' => [
            'header-name' => [
                'value' => 'header-value',
                'overwrite' => true,
            ],
        ],

        /**
         * Route-specific headers
         */
        'route-name' => [
            'header-name' => [
                'value' => 'header-value',
                'overwrite' => true,
            ]
        ],
    ]
]
```;

**Comment by marioradu05** [comment]
This issue was resolved in the following commit : https://github.com/dotkernel/dot-response-header/commit/f6a6b59eec09079f91a03359f3c58eaada74c260
