### ISSUE TITLE
cannot upgrade to 3.3.0 on api.

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-response-header#23]
composer require dotkernel/dot-response-header 3.3.0
./composer.json has been updated
Running composer update dotkernel/dot-response-header
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dotkernel/dot-response-header 3.3.0 -> satisfiable by dotkernel/dot-response-header[3.3.0].
    - dotkernel/dot-response-header 3.3.0 requires psr/http-message ^2.0 -> found psr/http-message[2.0] but the package is fixed to 1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by bidi47** [comment]
resolved in https://github.com/dotkernel/dot-response-header/pull/25
