### ISSUE TITLE
Existing header incorrect overwrite

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/dot-response-header#3]
If header exists, ResponseHeaderMiddleware:addHeaders tries to add same header with the new value - instead of overwriting it.
The below should be enough:
```php
    $overwrite = (isset($data['overwrite']) && $data['overwrite'] === true) ? true : false;
    if ($overwrite) {
        $response = $response->withHeader($header, $data['value']);
    }
```
Test config:
```php
    'dot_response_headers' => [
        '*' => [
            'permissions-policy' => [
                'value' => 'interest-cohort=()',
                'overwrite' => true,
            ],
        ],
        'home' => [
            'permissions-policy' => [
                'value' => 'foo'
            ]
        ],
    ]
```
The value of **permissions-policy** should stay **interest-cohort=()**

**Comment by marioradu05** [comment]
The issue was resolved in the following commit : https://github.com/dotkernel/dot-response-header/commit/a6debbd982a1f4a4102eb11dc3e233f0f13b2336
